export const pinnedRepos = [
    {
      id: 1,
      name: "gatsby-workshop",
      description: "This workshop covers the fundamentals of developing fast, accessible sites with Gatsby, a react framework, and dive deep into the building blocks you'll need to build your own custom Gatsby sites.",
      language: "JavaScript",
      stars: 38,
      forks: 8,
      },
      {
      id: 2,
      name: "React-Ladies",
      description: "We're a group of woemn and non-binary ReactJS ethusiasts in New York City (and beyond).",
      language: "JavaScript",
      stars: 99,
      forks: 26,
      },
      {
      id: 3,
      name: "getting-started-with-open-source",
      description: "This is a presentation on Getting Started With Open Source",
      language: "JavaScript",
      stars: 6,
      forks: null,
      },
          {
      id: 4,
      name: "httriri",
      description: "HTTRiRi - HTTP Status Codes as Portrayed by Rihanna GIFs ✨💄",
      language: "TypeScript",
      stars: 37,
      forks: 22,
      },
          {
      id: 5,
      name: "Rebuild-Black-Business/RBB-Website",
      description: "Websites to help connect black-owned businesses with consumers and resources",
      language: "JavaScript",
      stars: 99,
      forks: 75,
      },
      {
      id: 6,
      name: "affirmation_generator",
      description: "A random affirmation generator written with ReactJS :-)",
      language: "JavaScript",
      stars: 52,
      forks: 32,
      },
  ]
